 
version: 2.1
 
jobs:
  clean:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout 
        run: 
          name: Clean
          command: mvn clean -DskipTests
  
  build:
    docker:
      - image : cimg/openjdk:11.0
    steps:
      - checkout 
        run: 
          name: build
          command : mvn install -DskipTests

  test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout 
        run: 
          name: Test
          command: mvn test

workflows:
  sample: 
    jobs:
      - clean
      - build
      - test
