version: 2.1

orbs:
  maven: circleci/maven@1.4.1

jobs:
  clean:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn clean -DskipTests

workflows:
  sample:
    jobs:
      - clean
